# Generated by Django 4.2.4 on 2023-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_guard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
